### ISSUE TITLE
Unexpected results

### ISSUE THREAD

**Issue by hugopl** [acoustep/fuzzy_match.cr#2]
Hi, I'm trying out this shard but found some unexpected results:

To test it I used as source the list of files from fuzzy_match.cr itself plus a file named `main.cr`, when searching for `main` I would expect `src/main.cr` to have a bigger score than `lib/fuzzy_match/LICENSE`, but it hadn't.

I reduced the test-case and here is the output and the code that generated it.
```
search term: main
90 - lib/fuzzy_match/LICENSE
45 - lib/version_from_shard/LICENSE
30 - src/main.cr
30 - lib/fuzzy_match/.gitignore
30 - lib/fuzzy_match/src/fuzzy_match/version.cr
30 - lib/fuzzy_match/.tool-versions
30 - lib/fuzzy_match/.editorconfig
```
Search done with:
```crystal
  require "fuzzy_match"

  files = %w(
    src/main.cr
    lib/fuzzy_match/.gitignore
    lib/fuzzy_match/LICENSE
    lib/version_from_shard/LICENSE
    lib/fuzzy_match/src/fuzzy_match/version.cr
    lib/fuzzy_match/.tool-versions
    lib/fuzzy_match/.editorconfig
  )

  results = FuzzyMatch.search(ARGV[1], files)
  puts "search term: #{ARGV[1]}"
  results.each do |result|
    puts "#{result.score} - #{result.str}"
  end
```

**Comment by acoustep** [comment]
Thanks for reporting this. I'll see what I can find out - it seems that the sequential match bonus should be higher.

**Comment by acoustep** [comment]
After looking into it more it seems the issue is with giving out camel case bonuses at the wrong time. It will now check that the previous character is lowercase before giving the bonus. 

This will reduce the score on files like `lib/fuzzy_match/LICENSE` as the capital I and N were getting bonuses when they shouldn't have been.

I've also added a test that shows your scenario prioritises `src/main.cr`. So if you update to 0.3.0 this should be fixed.

**Comment by hugopl** [comment]
Thanks very much. I think the issue can be closed.
